/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import classes.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ManageMusicItems extends javax.swing.JFrame {

    /**
     * Creates new form ManageMusicItems
     */
    public ManageMusicItems() {
        initComponents();
        btnManageItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageItemSearchActionPerformed(evt);
            }
        });
        
    }
    
    
    
    private void clearFieldsExceptTitle() {
        txtMusicArtistManage.setText("");
        cmbMusicGenreManage.setSelectedIndex(0);
        cmbboxMusicFormateManage.setSelectedIndex(0);
        txtMusicItemPriceManage.setText("");
        txtMusicQuantityManage.setText("");
        txtMusicReleaseYearManage.setText("");
        txtMusicDescriptionManage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtMusicReleaseYearManage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMusicItemPriceManage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbMusicGenreManage = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbboxMusicFormateManage = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnMusicItemManage = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnMusicItemAddBack = new javax.swing.JButton();
        txtMusicTitleManage = new javax.swing.JTextField();
        txtMusicQuantityManage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMusicArtistManage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMusicDescriptionManage = new javax.swing.JTextArea();
        btnManageItemSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Genre");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Price");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Discription");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Artist");

        cmbMusicGenreManage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Genre", "Pop", "Rock", "Jazz", "Classical", "Hip-Hop", "Children's Music" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Format");

        cmbboxMusicFormateManage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Formate", "Albums", "Digital Tracks" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Quantity");

        btnMusicItemManage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMusicItemManage.setText("Update");
        btnMusicItemManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicItemManageActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Release Year");

        btnMusicItemAddBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMusicItemAddBack.setText("Back");
        btnMusicItemAddBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicItemAddBackActionPerformed(evt);
            }
        });

        txtMusicQuantityManage.setActionCommand("<Not Set>");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Manage Music Items");

        txtMusicDescriptionManage.setColumns(20);
        txtMusicDescriptionManage.setRows(5);
        jScrollPane2.setViewportView(txtMusicDescriptionManage);

        btnManageItemSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageItemSearch.setText("Search");
        btnManageItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageItemSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnMusicItemManage)
                        .addGap(18, 18, 18)
                        .addComponent(btnMusicItemAddBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMusicReleaseYearManage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtMusicTitleManage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMusicArtistManage)
                                            .addComponent(cmbMusicGenreManage, 0, 176, Short.MAX_VALUE)
                                            .addComponent(cmbboxMusicFormateManage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMusicItemPriceManage, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(txtMusicQuantityManage))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(btnManageItemSearch)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMusicTitleManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageItemSearch))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMusicArtistManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMusicGenreManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbboxMusicFormateManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMusicItemPriceManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMusicQuantityManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMusicReleaseYearManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMusicItemManage)
                    .addComponent(btnMusicItemAddBack))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusicItemManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicItemManageActionPerformed
           String title = txtMusicTitleManage.getText().trim();
        String artist = txtMusicArtistManage.getText().trim();
        String genre = cmbMusicGenreManage.getSelectedItem().toString();
        String format = cmbboxMusicFormateManage.getSelectedItem().toString();
        String priceStr = txtMusicItemPriceManage.getText().trim();
        String quantityStr = txtMusicQuantityManage.getText().trim();
        String yearStr = txtMusicReleaseYearManage.getText().trim();
        String description = txtMusicDescriptionManage.getText().trim();

        // 1. Validation checks
        if (title.isEmpty() || artist.isEmpty() || genre.equals("Select Genre") || format.equals("Select Formate")) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields and select valid dropdown options.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double price = Double.parseDouble(priceStr);
            int quantity = Integer.parseInt(quantityStr);
            int releaseYear = Integer.parseInt(yearStr);

            // Updated column name in UPDATE query: stock_quantity = ?
            String updateQuery = "UPDATE music_items SET artist = ?, genre = ?, format = ?, price = ?, stock_quantity = ?, release_year = ?, description = ? WHERE title = ?";

            try (Connection conn = DBConnection.getConnection();
                 PreparedStatement pstmt = conn.prepareStatement(updateQuery)) {

                pstmt.setString(1, artist);
                pstmt.setString(2, genre);
                pstmt.setString(3, format);
                pstmt.setDouble(4, price);
                pstmt.setInt(5, quantity); // Maps to stock_quantity column
                pstmt.setInt(6, releaseYear);
                pstmt.setString(7, description);
                pstmt.setString(8, title);

                int rowsAffected = pstmt.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Music item updated successfully!", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Update failed. No item found with title: " + title, "Update Failed", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price, Quantity, and Release Year must be valid numbers.", "Invalid Format", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnMusicItemManageActionPerformed

    private void btnMusicItemAddBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicItemAddBackActionPerformed
        new StoreManagerMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMusicItemAddBackActionPerformed

    private void btnManageItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageItemSearchActionPerformed
        String searchText = txtMusicTitleManage.getText().trim();

        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a value, letter, or word to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Uses LIKE %?% for partial string matching
        String query = "SELECT * FROM music_items WHERE title LIKE ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {

            // % surrounding the search string allows matching anywhere in the text
            pstmt.setString(1, "%" + searchText + "%");
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Fills fields with the first matching record
                txtMusicTitleManage.setText(rs.getString("title")); // Full title display
                txtMusicArtistManage.setText(rs.getString("artist"));
                cmbMusicGenreManage.setSelectedItem(rs.getString("genre"));
                cmbboxMusicFormateManage.setSelectedItem(rs.getString("format"));
                txtMusicItemPriceManage.setText(String.valueOf(rs.getDouble("price")));
                txtMusicQuantityManage.setText(String.valueOf(rs.getInt("stock_quantity"))); 
                txtMusicReleaseYearManage.setText(String.valueOf(rs.getInt("release_year")));
                txtMusicDescriptionManage.setText(rs.getString("description"));

                JOptionPane.showMessageDialog(this, "Record found!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No matching music item found for: " + searchText, "Not Found", JOptionPane.ERROR_MESSAGE);
                clearFieldsExceptTitle();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnManageItemSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMusicItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMusicItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMusicItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMusicItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMusicItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageItemSearch;
    private javax.swing.JButton btnMusicItemAddBack;
    private javax.swing.JButton btnMusicItemManage;
    private javax.swing.JComboBox<String> cmbMusicGenreManage;
    private javax.swing.JComboBox<String> cmbboxMusicFormateManage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtMusicArtistManage;
    private javax.swing.JTextArea txtMusicDescriptionManage;
    private javax.swing.JTextField txtMusicItemPriceManage;
    private javax.swing.JTextField txtMusicQuantityManage;
    private javax.swing.JTextField txtMusicReleaseYearManage;
    private javax.swing.JTextField txtMusicTitleManage;
    // End of variables declaration//GEN-END:variables
}
