/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

public class StoreManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form StoreManagerMenu
     */
    public StoreManagerMenu() {
        initComponents();
        addButtonEffects(addUsers);
        addButtonEffects(searchUsers);
        addButtonEffects(addMusicItem);
        addButtonEffects(manageMusicItems);
        addButtonEffects(addPromotion);
        addButtonEffects(searchPromotions);
        addButtonEffects(searchSalesDetails);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addUsers = new javax.swing.JButton();
        searchUsers = new javax.swing.JButton();
        addMusicItem = new javax.swing.JButton();
        manageMusicItems = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addPromotion = new javax.swing.JButton();
        searchPromotions = new javax.swing.JButton();
        searchSalesDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Store Manager Menu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("User Management");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Pricing Management");

        addUsers.setBackground(new java.awt.Color(0, 153, 255));
        addUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addUsers.setForeground(new java.awt.Color(255, 255, 255));
        addUsers.setText("Add New User");
        addUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsersActionPerformed(evt);
            }
        });

        searchUsers.setBackground(new java.awt.Color(0, 153, 255));
        searchUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchUsers.setForeground(new java.awt.Color(255, 255, 255));
        searchUsers.setText("Search User Details");
        searchUsers.setActionCommand("Search User Details");
        searchUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        searchUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUsersActionPerformed(evt);
            }
        });

        addMusicItem.setBackground(new java.awt.Color(0, 153, 255));
        addMusicItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addMusicItem.setForeground(new java.awt.Color(255, 255, 255));
        addMusicItem.setText("Add Music Item");
        addMusicItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addMusicItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMusicItemActionPerformed(evt);
            }
        });

        manageMusicItems.setBackground(new java.awt.Color(0, 153, 255));
        manageMusicItems.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageMusicItems.setForeground(new java.awt.Color(255, 255, 255));
        manageMusicItems.setText("Search Items");
        manageMusicItems.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manageMusicItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMusicItemsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Promotion Details");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sales Reports");

        addPromotion.setBackground(new java.awt.Color(0, 153, 255));
        addPromotion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addPromotion.setForeground(new java.awt.Color(255, 255, 255));
        addPromotion.setText("Add New Promotion");
        addPromotion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPromotionActionPerformed(evt);
            }
        });

        searchPromotions.setBackground(new java.awt.Color(0, 153, 255));
        searchPromotions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchPromotions.setForeground(new java.awt.Color(255, 255, 255));
        searchPromotions.setText("Search Promotion Details");
        searchPromotions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        searchPromotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPromotionsActionPerformed(evt);
            }
        });

        searchSalesDetails.setBackground(new java.awt.Color(0, 153, 255));
        searchSalesDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchSalesDetails.setForeground(new java.awt.Color(255, 255, 255));
        searchSalesDetails.setText("Search Sales Details");
        searchSalesDetails.setToolTipText("");
        searchSalesDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        searchSalesDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchSalesDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchSalesDetailsMouseExited(evt);
            }
        });
        searchSalesDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSalesDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchPromotions, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPromotion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchSalesDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addMusicItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageMusicItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMusicItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageMusicItems, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSalesDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchPromotions, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUsersActionPerformed
        new SearchUserDetails().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchUsersActionPerformed

    private void addMusicItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMusicItemActionPerformed
        new AddMusicItems().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addMusicItemActionPerformed

    private void manageMusicItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMusicItemsActionPerformed
        new SearchMusicItems().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageMusicItemsActionPerformed

    private void searchPromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPromotionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPromotionsActionPerformed

    private void addPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPromotionActionPerformed

    private void searchSalesDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSalesDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSalesDetailsActionPerformed

    private void searchSalesDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchSalesDetailsMouseEntered
       
    }//GEN-LAST:event_searchSalesDetailsMouseEntered

    private void searchSalesDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchSalesDetailsMouseExited
       
    }//GEN-LAST:event_searchSalesDetailsMouseExited

    private void addUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsersActionPerformed
        new User().setVisible(true);
        this.dispose();     
    }//GEN-LAST:event_addUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreManagerMenu().setVisible(true);
            }
        });
    }
    
  

    private void addButtonEffects(javax.swing.JButton button) {
        final java.awt.Color normalColor = new java.awt.Color(0, 153, 255);
        final java.awt.Color hoverColor = new java.awt.Color(0, 110, 200);
        final java.awt.Color pressedColor = new java.awt.Color(0, 80, 160);

        button.setOpaque(true);
        button.setContentAreaFilled(true);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        button.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(normalColor);
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button.setBackground(pressedColor);
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                // If mouse is still over the button when released, go back to hover color;
                // otherwise return to normal (handles drag-off-and-release correctly)
                if (button.contains(evt.getPoint())) {
                    button.setBackground(hoverColor);
                } else {
                    button.setBackground(normalColor);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMusicItem;
    private javax.swing.JButton addPromotion;
    private javax.swing.JButton addUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton manageMusicItems;
    private javax.swing.JButton searchPromotions;
    private javax.swing.JButton searchSalesDetails;
    private javax.swing.JButton searchUsers;
    // End of variables declaration//GEN-END:variables
}
